// This file is auto-generated by scripts/generate-version.mjs - do not run manually unless
// regenerating ../src/environments/version.ts. The generated file is gitignored.
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { writeFileSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..', '..');
const outputFile = resolve(__dirname, '..', 'src', 'environments', 'version.ts');

function run(command) {
  return execSync(command, { cwd: repoRoot, encoding: 'utf-8' }).trim();
}

let version = 'unknown';
try {
  version = run('git describe --tags --always --dirty');
} catch {
  version = 'unknown';
}

let branch = 'unknown';
try {
  branch = run('git rev-parse --abbrev-ref HEAD');
} catch {
  branch = 'unknown';
}

const content = `// This file is auto-generated by scripts/generate-version.mjs - do not edit manually.
export const VERSION = {
  version: '${version}',
  branch: '${branch}',
};
`;

writeFileSync(outputFile, content, 'utf-8');

console.info(`Generated ${outputFile} (version: ${version}, branch: ${branch})`);
